### PR TITLE
Cluster request timeout now throws TimeoutException

### LINKED ISSUE #1712: Make Cluster.RequestAsync throw exception instead of returning null
Currently, Cluster.RequestAsync will return null for timeouts, this is an old design based on the fact that exceptions are expensive in .NET. it is however non-obvious and problematic to communicate to users.

Instead, I think we should use proper exceptions here.
This could also have a setting in ClusterConfig, so that it can be set to the old behavior for compatibility.

### PR DESCRIPTION
**Pull request by marcinbudny**
## Description

Closes #1712 

Cluster requests now throw TimeoutException on timeout. This is a breaking change. Old behavior can be enabled via `ClusterConfig.WithLegacyRequestTimeoutBehavior()`

## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs [hunk 1]
```diff
@@ -96,7 +96,19 @@ public void RemoveActivations()
             tasks[i] = _cluster.RequestAsync<Terminated>(id, PoisonPill.Instance, cts.Token);
         }
 
-        Task.WhenAll(tasks).GetAwaiter().GetResult();
+        try
+        {
+            Task.WhenAll(tasks).GetAwaiter().GetResult();
```
Comment (mhelleborg) [inline benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: This will be a change in behaviour.. but not sure it's a problem in this context

File: tests/Proto.Cluster.Tests/ClusterTests.cs [hunk 2]
```diff
@@ -57,6 +57,14 @@ public async Task HandlesSlowResponsesCorrectly()
         response.Message.Should().Be(msg);
     }
 
+    [Fact]
+    public async Task ThrowsWhenTimeoutExceeded()
+        => await Members.First()
+            .Invoking(m => m.RequestAsync<Pong>(CreateIdentity("slow-test"), EchoActor.Kind,
+                    new SlowPing {Message = "hi", DelayMs = 5000}, new CancellationTokenSource(2000).Token
```
Comment (mhelleborg) [inline tests/Proto.Cluster.Tests/ClusterTests.cs]: The timeout here might be even lower, to provide for a faster test?

File: tests/Proto.Cluster.Tests/LegacyTimeoutTests.cs [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+public class LegacyTimeoutTests
+{
+    [Fact]
+    public async Task ReturnsNullOnTimeoutInLegacyMode()
+    {
+        await using var fixture = new Fixture(1);
+        await fixture.InitializeAsync();
+
+        var response = await fixture.Members.First().RequestAsync<Pong>(CreateIdentity("slow-test"), EchoActor.Kind,
+            new SlowPing {Message = "hi", DelayMs = 5000}, new CancellationTokenSource(2000).Token
```
Comment (mhelleborg) [inline tests/Proto.Cluster.Tests/LegacyTimeoutTests.cs]: Shorter timeout?

File: src/Proto.Cluster/DefaultClusterContext.cs [hunk 4]
```diff
@@ -110,15 +112,14 @@ public DefaultClusterContext(Cluster cluster)
                             return t1;
                         }
 
-                        if (typeof(T) == typeof(MessageEnvelope))
+                        if (untypedResult == null) // TODO: what if request response is actually null?
```
Comment (rogeralsing) [inline src/Proto.Cluster/DefaultClusterContext.cs]: It cannot be. null is not an allowed message

File: benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs (hunk 1 above)
Comment (marcinbudny) [reply benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: Not sure what you mean. The previous version ignored timeouts and the catch I added does is meant to reproduce this behavior with the new version. 

Overall the behavior of Benchmark.NET is a bit weird when exception is thrown in the cleanup method. It seems to ignore it but then benchmark  crashes on super weird issues.

Comment (mhelleborg) [reply benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: The block ignores it, but it does not wait for the remaining tasks? Previously each call "suppressed" the timeout, now it should throw on the first failing call?

Comment (mhelleborg) [reply benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: Anyways, it's a benchmark, not critical path :)

Not too concerned if the semantics changed a little there

Comment (marcinbudny) [reply benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: Task.WhenAll waits for all tasks even if one of the fails. Am I missing something here?

File: tests/Proto.Cluster.Tests/ClusterTests.cs (hunk 2 above)
Comment (marcinbudny) [reply tests/Proto.Cluster.Tests/ClusterTests.cs]: Moved to separate class and experimented with timeout length. It seems that for netcoreapp3.1 target (where we use TaskClock) 4 seconds is a min for this no to fail in CI.

File: tests/Proto.Cluster.Tests/LegacyTimeoutTests.cs (hunk 3 above)
Comment (marcinbudny) [reply tests/Proto.Cluster.Tests/LegacyTimeoutTests.cs]: It seems that for netcoreapp3.1 target (where we use TaskClock) 4 seconds is a min for this no to fail in CI.

File: benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs (hunk 1 above)
Comment (marcinbudny) [reply benchmarks/ClusterMicroBenchmarks/ConcurrentSpawnBenchmark.cs:101]: Ping @mhelleborg 
Should I just resolve this?
